branch-defaults:
  master:
    environment: whohw-stage
environment-defaults:
  whohw-stage:
    branch: null
    repository: null
global:
  application_name: WHoWH Temp
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Node.js running on
    64bit Amazon Linux/4.8.3
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: totem
  sc: git
  workspace_type: Application
